### ISSUE TITLE
broken

### ISSUE THREAD

**Issue by ecommercedegree** [Fexa/remove_darkrp_restricted_tools#1]
Prevents people using the qmenu at a all. Happens quite often to a few select players randomly

cl_rdrt.lua:224: attempt to call method 'GetList' (a nil value)
1. remove_tool - addons/sebs/lua/autorun/client/cl_rdrt.lua:224
2. fn - addons/sebs/lua/autorun/client/cl_rdrt.lua:251
3. Call - addons/ulib/lua/ulib/shared/hook.lua:109
4. unknown - gamemodes/base/gamemode/cl_spawnmenu.lua:56
5. unknown - lua/includes/modules/concommand.lua:54
[dmaaaar|27|STEAM_0:0:83865714] Lua Error:

**Comment by Fexa** [comment]
fixed by adding
`if _v.GetList then`
to line 42
